[project]
name = 'finmarketpy'
version = "0.11.19"
description = "finmarketpy is a Python based library for backtesting trading strategies"
authors = [{name='Saeed Amen', email= 'saeed@cuemacro.com'}]
readme = "README.md"
requires-python = "==3.13.*"
license = {text = "Apache-2.0"}
dependencies = [
    "blosc>=1.11.3",
    "chartpy>=0.1.16",
    "findatapy>=0.1.40",
    "matplotlib>=3.10.7",
    "multiprocess>=0.70.18",
    "numba>=0.62.1",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pytz>=2025.2",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "seasonal>=0.3.1",
    "twython>=3.9.1",
]
keywords = [
    "trading", "markets", "currencies", "pandas", "data", "Bloomberg", "tick", "stocks", "equities"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]

[project.urls]
repository = "https://github.com/cuemacro/finmarketpy"
Homepage = "https://github.com/cuemacro/finmarketpy"

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "pre-commit>=4.0.1",
    "deptry>=0.23.0",
    "marimo>=0.11.16",
]

[tool.ruff]
line-length = 120
target-version = "py313"
exclude = [
    "*__init__.py"
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["finmarketpy"]

[tool.hatch.build]
include = [
    "LICENSE",    # Ensure the LICENSE file is included in your package
    "README.md",
    "finmarketpy"
]

[tool.bandit]
exclude_dirs = ["tests"]

[tool.deptry.per_rule_ignores]
#DEP001 = ["pyfolio"]       # very dated dependency!
DEP003 = ["finmarketpy"]
